language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip install -r dev-requirements.txt
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: pypi
  username: __token__
  server: https://test.pypi.org/legacy/
  skip_existing: true
  on:
    branch: develop
  password:
    secure: GD7pl9tRux5cJ5ITJ3VW3iBF1VQV7HiBnU+VF2pmOkAAdstAHXNDjNTHnMqRQTTAUKBi2WyFIn3uHKRWvBYLochaBRuS3T7lomOn2W0hPl+0jMMTUKxfz4eXU/cZLw8Yvo/C7rxAjvhp2Uxb12jpC7Sd0kuMT+N96NUrTmZ9a0wuJzfl4sGdTgdESliCyrSnXYRgeTLTb4kfzcb5eY95fvtrjDOuZuW3IGdNEimpvz9Nx0Yc8YO3ZEzzAzaVDiSx941doeJ0401MyGQWIfeX6uqx8U1tUeq+/++0zQjZmF0yTSaV+pyTyZ/CCrMnFw7c6kW/PojHTJvonfKMteUNxc1v0YyLHE5SoZ7UcJttzAVN9m/TMIB9QEWSkNKYtAzE7zOj16I+2qKPyAorKFyw0mmjyoaDYtJqQl62PoXEYxceHH/PpJPdhtszS7YI0VYXJrWQ5w7pu8rJDgVdsp7I2BcfgwH5ktQOXLJA34O8x21GzbAUuSnQ8NN+PMwtqSqSFajoh8fTo2j1eR4IH3CjNizjbS3/9byolLgxO0s12WUObMyu2psol+qIQ7sqMaNALl8REx33w16banJpW/7RAvV2zi5aRHRclEHCLE8huGlpoGYKbCy6EIBfC6Kljvp3uTMvKadbkSs2H6JDw8lk3sfUAmOzT63cJwXfiSWFaFw=
