# From https://github.com/keycloak/keycloak-containers.git
version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mariadb:
      image: mariadb:10.5
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      # Copy-pasted from https://github.com/docker-library/mariadb/issues/94
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
  keycloak:
      image: jboss/keycloak:13.0.1
      environment:
        DB_VENDOR: mariadb
        DB_ADDR: mariadb
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        KEYCLOAK_LOGLEVEL: INFO
        JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
        JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500
        KEYCLOAK_IMPORT: "/tmp/realm-export.json"
      volumes:
        - ./realm-export.json:/tmp/realm-export.json
      depends_on:
        - mariadb
      ports:
        - 127.0.0.1:8080:8080
        - 127.0.0.1:8443:8443
